apiVersion: v2
name: pagopa-iuvgenerator
description: Microservice that permits to generate unique IUV codes for each creditor institution.
type: application
version: 0.22.0
appVersion: 0.3.0
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
