microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-iuvgenerator
    tag: "0.2.14"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.shared.internal.dev.platform.pagopa.it"
    path: /pagopa-iuvgenerator(/|$)(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "shared-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaiuvgenerator' # required to show cloud role name in application insights
    ENV: 'dev'
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    OTEL_SERVICE_NAME: "pagopa-iuvgenerator"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: 'otlp'
    OTEL_METRICS_EXPORTER: 'otlp'
    OTEL_LOGS_EXPORTER: 'none'
    OTEL_TRACES_SAMPLER: "always_on"
    GENERATION_MAXRETRIES: '5'
  secretProvider:
    create: true
    envSecrets:
      # required
      APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
      OTEL_EXPORTER_OTLP_HEADERS: 'elastic-apm-secret-token'
      TABLE_CONNECTION_STRING: 'iuv-generator-cosmos-primary-connection-string'
    keyvault:
      name: "pagopa-d-shared-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: "0.0.1"
    create: false
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>